### ISSUE TITLE
Do you have a BOM?

### ISSUE THREAD

**Issue by spaelectronics** [chimera/laser-cutter-control#1]
Is there any way I could get a BOM for this?

**Comment by danawoodman** [comment]
@randybuildsthings is the mastermind behind this, maybe he can help

**Comment by jegb** [comment]
Last summer I designed similar board, but with an addition to use grbl shield to plug an arduino under it (in case that you want to avoid PC parallel port). Not sure how much traction this will get with Smoothie, LaOS, and the marlin/mega/ramps combo operating in same space. I also went with multiple isolators on same chip, bom and assembly costs could be competitive compared to these options though.

**Comment by randybuildsthings** [comment]
Sorry guys, been off fighting other battles away from Github.

There is no BOM available at this time. I would have to crack open the EAGLE CAD files and have a look. It may very well be that I've partially specified the parts inside of EAGLE, and a BOM could be constructed from that. Let's just say that I'm not in as big a hurry to do this as I was a year ago. Sorry I can't be more help here.

**Comment by randybuildsthings** [comment]
And @jegb this project clearly didn't get traction with Smoothie, I had several conversations with the devs for Smoothie and was vying for a board to use for development of the laser cutter. As I said, I've moved onto other things at the moment and don't have a timetable for developing this further.
